spring:
  jackson:
    default-property-inclusion: non_null
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8090
  boot:
    admin:
      client:
        url: http://localhost:8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
  instance:
    preferIpAddress: true
