spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
  zipkin:
    base-url: http://zipkin-server:8090
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8089/eureka/
