spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://users-postgres-server-service/users
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
