version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  configuration_server:
    image: training/configuration-server
    ports:
      - 8888
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  departments_database:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=departments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/departments:/var/lib/postgresql/data/application
