version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  configuration-server:
    image: training/configuration-server
    ports:
      - 8888
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  discovery-server:
    image: training/discovery-server
    ports:
      - 8089:8089
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  departments-database:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=departments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/departments:/var/lib/postgresql/data/application
  departments:
    image: training/departments
    ports:
      - 8000
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production
  users-database:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/users:/var/lib/postgresql/data/application
  users:
    image: training/users
    ports:
      - 8000
    environment:
      - CONFIGURATION_SERVER=configuration-server
      - CONFIGURATION_SERVER_PORT=8888
      - SLEEP_TIME=1
      - DEFAULT_PROFILE=production